"""
DocForge Excel Generator — excel.py
Uses openpyxl to produce styled .xlsx files.
Best for lab reports and data-heavy documents.
"""

from io import BytesIO
from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter
from bs4 import BeautifulSoup, NavigableString
import datetime


XLSX_THEMES = {
    "blue":   {"primary": "1A237E", "accent": "1565C0", "light": "E3F2FD", "mid": "90CAF9"},
    "purple": {"primary": "4A148C", "accent": "7B1FA2", "light": "F3E5F5", "mid": "CE93D8"},
    "green":  {"primary": "1B5E20", "accent": "2E7D32", "light": "E8F5E9", "mid": "A5D6A7"},
    "red":    {"primary": "B71C1C", "accent": "C62828", "light": "FFEBEE", "mid": "EF9A9A"},
    "dark":   {"primary": "1A1A2E", "accent": "0F3460", "light": "E8EAF6", "mid": "90A4AE"},
}

THIN_BORDER = Border(
    left=Side(style="thin", color="CCCCCC"),
    right=Side(style="thin", color="CCCCCC"),
    top=Side(style="thin", color="CCCCCC"),
    bottom=Side(style="thin", color="CCCCCC"),
)
MEDIUM_BORDER = Border(
    left=Side(style="medium", color="AAAAAA"),
    right=Side(style="medium", color="AAAAAA"),
    top=Side(style="medium", color="AAAAAA"),
    bottom=Side(style="medium", color="AAAAAA"),
)


def generate_excel(data: dict) -> bytes:
    """Generate a styled .xlsx file from document data."""
    theme = XLSX_THEMES.get(data.get("theme", "blue"), XLSX_THEMES["blue"])
    wb = Workbook()

    # ── Cover / Info sheet ──────────────────────────────────────
    ws_info = wb.active
    ws_info.title = "Document Info"
    ws_info.sheet_view.showGridLines = False
    ws_info.column_dimensions["A"].width = 22
    ws_info.column_dimensions["B"].width = 45

    _build_info_sheet(ws_info, data, theme)

    # ── Content sheet ───────────────────────────────────────────
    ws_content = wb.create_sheet("Content")
    ws_content.sheet_view.showGridLines = False
    ws_content.column_dimensions["A"].width = 15
    ws_content.column_dimensions["B"].width = 70

    _build_content_sheet(ws_content, data, theme)

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ══════════════════════════════════════════════════════════════
#  INFO SHEET — Cover-style metadata
# ══════════════════════════════════════════════════════════════

def _build_info_sheet(ws, data, theme):
    row = 1

    # Title banner
    ws.merge_cells(f"A{row}:B{row}")
    cell = ws[f"A{row}"]
    cell.value = data.get("title", "Untitled Document").upper()
    cell.font = Font(name="Calibri", size=18, bold=True, color="FFFFFF")
    cell.fill = PatternFill("solid", fgColor=theme["primary"])
    cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[row].height = 40
    row += 1

    # Document type row
    ws.merge_cells(f"A{row}:B{row}")
    doc_type = {
        "assignment": "Assignment", "report": "Academic Report",
        "cover_letter": "Cover Letter", "resume": "Curriculum Vitae",
        "lab_report": "Laboratory Report", "meeting_notes": "Meeting Minutes",
        "blank": "Document",
    }.get(data.get("type", "blank"), "Document")
    cell = ws[f"A{row}"]
    cell.value = doc_type.upper()
    cell.font = Font(name="Calibri", size=10, color="FFFFFF")
    cell.fill = PatternFill("solid", fgColor=theme["accent"])
    cell.alignment = Alignment(horizontal="center")
    ws.row_dimensions[row].height = 20
    row += 2

    # Metadata rows
    meta = []
    if data.get("author"):      meta.append(("Author",      data["author"]))
    if data.get("subject"):     meta.append(("Subject",     data["subject"]))
    if data.get("institution"): meta.append(("Institution", data["institution"]))
    date = data.get("date") or datetime.date.today().strftime("%B %d, %Y")
    meta.append(("Date", date))
    meta.append(("Generated By", "DocForge — FocusFlow"))

    for i, (k, v) in enumerate(meta):
        bg = theme["light"] if i % 2 == 0 else "FFFFFF"
        # Key cell
        kc = ws[f"A{row}"]
        kc.value = k
        kc.font = Font(name="Calibri", size=10, bold=True, color="444444")
        kc.fill = PatternFill("solid", fgColor=bg)
        kc.border = THIN_BORDER
        kc.alignment = Alignment(vertical="center")
        ws.row_dimensions[row].height = 22
        # Value cell
        vc = ws[f"B{row}"]
        vc.value = v
        vc.font = Font(name="Calibri", size=10, color="1A1A1A")
        vc.fill = PatternFill("solid", fgColor=bg)
        vc.border = THIN_BORDER
        vc.alignment = Alignment(vertical="center")
        row += 1

    row += 1
    # Footer note
    ws.merge_cells(f"A{row}:B{row}")
    nc = ws[f"A{row}"]
    nc.value = "Generated by DocForge — FocusFlow Document Engine"
    nc.font = Font(name="Calibri", size=8, italic=True, color="999999")
    nc.alignment = Alignment(horizontal="center")


# ══════════════════════════════════════════════════════════════
#  CONTENT SHEET — Document body
# ══════════════════════════════════════════════════════════════

def _build_content_sheet(ws, data, theme):
    html = data.get("html_content", "")
    if not html or html.strip() in ("", "<p></p>"):
        ws["A1"].value = "No content available."
        ws["A1"].font = Font(name="Calibri", size=10, italic=True, color="999999")
        return

    soup = BeautifulSoup(html, "html.parser")
    row = 1

    def _banner(text, bg, fg="FFFFFF", size=12):
        nonlocal row
        ws.merge_cells(f"A{row}:B{row}")
        c = ws[f"A{row}"]
        c.value = text
        c.font = Font(name="Calibri", size=size, bold=True, color=fg)
        c.fill = PatternFill("solid", fgColor=bg)
        c.alignment = Alignment(horizontal="left", vertical="center", indent=1)
        ws.row_dimensions[row].height = 28
        row += 1

    def _text(label, value, bg="FFFFFF"):
        nonlocal row
        kc = ws[f"A{row}"]
        kc.value = label
        kc.font = Font(name="Calibri", size=9, bold=True, color="555555")
        kc.fill = PatternFill("solid", fgColor=bg)
        kc.border = THIN_BORDER
        kc.alignment = Alignment(vertical="top", wrap_text=True)
        ws.row_dimensions[row].height = max(18, len(str(value)) // 4)

        vc = ws[f"B{row}"]
        vc.value = value
        vc.font = Font(name="Calibri", size=10, color="1A1A1A")
        vc.fill = PatternFill("solid", fgColor=bg)
        vc.border = THIN_BORDER
        vc.alignment = Alignment(vertical="top", wrap_text=True)
        row += 1

    def _gap():
        nonlocal row
        ws.row_dimensions[row].height = 8
        row += 1

    ol_counter = [0]

    for el in soup.children:
        if isinstance(el, NavigableString):
            t = str(el).strip()
            if t:
                _text("", t)
            continue
        tag = el.name
        if not tag:
            continue

        if tag == "h1":
            _gap()
            _banner(el.get_text(strip=True), theme["primary"], size=13)
        elif tag == "h2":
            _gap()
            _banner(el.get_text(strip=True), theme["accent"], size=11)
        elif tag == "h3":
            _banner(el.get_text(strip=True), theme["light"], fg=theme["accent"], size=10)
        elif tag == "p":
            txt = el.get_text(strip=True)
            if txt:
                bg = "FFFFFF" if row % 2 == 0 else "FAFAFA"
                _text("", txt, bg)
        elif tag == "ul":
            for li in el.find_all("li", recursive=False):
                _text("•", li.get_text(strip=True))
        elif tag == "ol":
            for i, li in enumerate(el.find_all("li", recursive=False), 1):
                _text(f"{i}.", li.get_text(strip=True))
        elif tag == "blockquote":
            ws.merge_cells(f"A{row}:B{row}")
            c = ws[f"A{row}"]
            c.value = f'"{el.get_text(strip=True)}"'
            c.font = Font(name="Calibri", size=10, italic=True, color="666666")
            c.fill = PatternFill("solid", fgColor="F5F5F5")
            c.alignment = Alignment(wrap_text=True, indent=2)
            ws.row_dimensions[row].height = 24
            row += 1
        elif tag == "table":
            _gap()
            headers = []
            rows_data = []
            thead = el.find("thead")
            tbody = el.find("tbody") or el
            if thead:
                headers = [th.get_text(strip=True) for th in thead.find_all("th")]
            for tr in tbody.find_all("tr"):
                r = [td.get_text(strip=True) for td in tr.find_all(["td", "th"])]
                if r:
                    rows_data.append(r)
            if not headers and rows_data:
                headers = rows_data.pop(0)

            n_cols = max(len(headers), max((len(r) for r in rows_data), default=1), 1)
            # Set column widths
            for j in range(n_cols):
                col_letter = get_column_letter(j + 1)
                ws.column_dimensions[col_letter].width = 25

            # Header
            for j, h in enumerate(headers[:n_cols]):
                c = ws.cell(row=row, column=j + 1)
                c.value = h
                c.font = Font(name="Calibri", size=9, bold=True, color="FFFFFF")
                c.fill = PatternFill("solid", fgColor=theme["accent"])
                c.border = THIN_BORDER
                c.alignment = Alignment(horizontal="center")
            ws.row_dimensions[row].height = 22
            row += 1

            for ri, row_data in enumerate(rows_data):
                bg = theme["light"] if ri % 2 == 1 else "FFFFFF"
                for j in range(n_cols):
                    c = ws.cell(row=row, column=j + 1)
                    c.value = row_data[j] if j < len(row_data) else ""
                    c.font = Font(name="Calibri", size=9)
                    c.fill = PatternFill("solid", fgColor=bg)
                    c.border = THIN_BORDER
                    c.alignment = Alignment(wrap_text=True)
                ws.row_dimensions[row].height = 18
                row += 1
            _gap()

        elif tag == "hr":
            ws.merge_cells(f"A{row}:B{row}")
            c = ws[f"A{row}"]
            c.border = Border(bottom=Side(style="medium", color=theme["accent"]))
            row += 1
